name: 'basic-check'
description: 'Test actions reusability'
inputs:
  os-version:  # id of input
    description: 'OS version'
    required: true
    default: 'ubuntu-latest'
runs:
  using: "composite"
  steps:
    - name: StartAction
      run: echo 'START ACTION STEPS DOORS'
      shell: bash
    - name: Chmode gradlew
      if: ${{ ! contains(inputs.os-version, 'windows') }}
      run: chmod +x ./gradlew
      shell: bash
    - name: Compile
      run: ./gradlew compileKotlin
      shell: bash
    - name: Kotlin style check
      run: ./gradlew ktlintCheck
      shell: bash
    - name: Build
      run: ./gradlew build
      shell: bash
    - name: Test
      run: ./gradlew test
      shell: bash
