name: 'basic-check'
description: 'Test actions reusability'
runs:
  using: "composite"
  steps:
    - name: StartAction
      run: echo 'START ACTION STEPS DOORS'
      shell: bash
    - name: Compile
      run: ./gradlew compileKotlin
      shell: bash
    - name: Kotlin checks
      run: ./gradlew check
      shell: bash
