name: workflow
on: 
  push
jobs:
  Build:
    name: Build
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        java: [ 15 ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: test1
        run: |
          git status
          git pull
          git status
          git log -2
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Chmode gradlew
        if: ${{ ! contains(matrix.os, 'windows') }}
        run: chmod +x ./gradlew
      - name: ActionChecks
        uses: ./.github/actions
      - name: DoneAction
        run: echo 'All steps from action DONE'
  VersionUpdate:
    needs: Build
    if: ${{ contains(github.ref, 'refs/tags/') }}
    name: Version update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: log commit
        run: |
          git pull
          git log -2
      - name: Set up JDK 
        uses: actions/setup-java@v1
        with:
          java-version: 15
      - name: Chmode gradlew
        run: chmod +x ./gradlew
      - name: Manual tag
        run: |
          git describe || echo "0.1.0-$(git log -n1 --date=format:'%Y-%m-%dT%H%M%S' --format=%cd)"
          git describe --abbrev=0 || echo "0.1.0-$(git log -n1 --date=format:'%Y-%m-%dT%H%M%S' --format=%cd)"
      - name: Update version
        run: ./gradlew computeVersion
      - name: Commit and push
        uses: EndBug/add-and-commit@v7
        with:
          author_name: Giordo
          add: 'README.md'
          message: 'updated version'
          branch: main
          push: true