name: workflow
on: 
  push
jobs:
  Build:
    name: Build
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        java: [ 12, 15 ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: ActionChecks
        id: all-check
        uses: actions/basic-check@v1
        with:
          jdk-version: ${{ matrix.java }}
          os-version: ${{ matrix.os }}
      - name: DoneAction
        run: echo 'All steps from action DONE'
