name: workflow
on: 
  push
jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 
        uses: actions/setup-java@v1
        with:
          java-version: 15
      - name: Chmode gradlew
        if: ${{ ! contains(matrix.os, 'windows') }}
        run: chmod +x ./gradlew
      - name: ActionChecks
        uses: ./.github/actions
      - name: DoneAction
        run: echo 'All steps from action DONE'
  VersionUpdate:
    if: ${{ contains(github.ref, 'refs/tags/') }}
    name: Version update
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        run: |
          git clone https://github.com/Giordo94/TestAction
          echo "DONE git clone"
          ls -l
          cd TestAction
          echo "inside TestAction"
          ls -l
          echo "DONE ls inside TestAction"
          git checkout develop
          echo "checkout develop DONE"
          git status
          echo "hopefully nothing to commit"
          git log -4
          echo "DONE logging info"
          ls -l
          echo "DONE ls after checkout develop"
          echo "describe full tag"
          git describe || echo "0.1.0-$(git log -n1 --date=format:'%Y-%m-%dT%H%M%S' --format=%cd)"
          echo "describe short tag"
          git describe --abbrev=0 || echo "0.1.0-$(git log -n1 --date=format:'%Y-%m-%dT%H%M%S' --format=%cd)"
          echo "DONE describe tag"
      - name: Set up JDK 
        uses: actions/setup-java@v1
        with:
          java-version: 15
      - name: Chmode gradlew
        run: |
          ls -l
          echo "DONE ls before chmod"
          chmod +x ./gradlew
      - name: Update version
        run: ./gradlew computeVersion
      - name: Commit and push
        uses: EndBug/add-and-commit@v7
        with:
          author_name: Giordo
          add: 'README.md'
          message: 'updated version'
          branch: main
          push: true