name: workflow
env:
  branch: develop
on: 
  push
jobs:
  CheckAll:
    name: CheckAll
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        java: [ 1.8, 15 ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Chmode gradlew
        run: chmod +x ./gradlew
      - name: ActionChecks
        uses: ./.github/actions
      - name: DoneAction
        run: echo 'All steps from action DONE'
  VersionUpdate:
    if: ${{ contains(github.ref, 'refs/tags/') }}
    name: Version update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 
        uses: actions/setup-java@v1
        with:
          java-version: 15
      - name: fetch all tags to fix broken checkout
        run: git fetch --force --tags
      - name: Chmode gradlew
        run: chmod +x ./gradlew
      - name: Update version
        run: ./gradlew computeVersion
      - name: Assemble dist
        run: ./gradlew assembleDist
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            LICENSE
            ./build/distributions/*.zip
            ./build/distributions/*.tar
      - name: Commit and push
        uses: EndBug/add-and-commit@v7
        with:
          author_name: Giordo
          add: 'README.md'
          message: 'updated version'
          branch: ${{ env.branch }}
          push: true
